spring.application.name=WeatherMood

spring.datasource.url=jdbc:mysql://localhost:3306/weathermood_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
#spring.datasource.password=??_mysql_????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=weathermood-jwt-secret-key-weathermood-jwt-secret-key-1234567890
jwt.expiration=86400000

weather.api.key=e88aa86bd17765e972ccb51249a892a1
weather.api.city=Seoul

tmdb.api.key=95661336bee3380caf09ff1934ccf339